// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel Demo

//variables
RWTexture2D<float4> Result;
uniform float Time;

[numthreads(8,8,1)]
void Demo (uint3 id : SV_DispatchThreadID)
{    
    float speed = 2;
    float pi = 3.14;

    float rTime = sin(speed*Time);
    float gTime = cos(speed*Time);
    float bTime = sin(speed*Time + pi);
    
    Result[id.xy] = float4(rTime, gTime, bTime, 1);
}